import { LINKS } from "../data/links";
import { currentSnapshot, type DriftProfile } from "../data/telemetry";
import type { NetworkLink, TelemetryPoint } from "../data/types";
import telemetryData from "../data/generated/telemetry.json";
import driftProfilesData from "../data/generated/drift-profiles.json";

/** Maps each of the six approved corridors to the shape of its 48h telemetry.
 *  This is the single place a link's "story" (stable vs. drifting vs.
 *  recovering) is declared — and it is declared in the Python engine
 *  (engine/netsense/profiles.py), which also generates the telemetry below. */
export const DRIFT_PROFILES = driftProfilesData as Record<string, DriftProfile>;

const telemetryByLink = telemetryData as unknown as Record<string, TelemetryPoint[]>;

/** Synthetic 30-minute telemetry for a link, generated by the Python engine
 *  (src/data/generated/telemetry.json) — not measured from any network. */
export function getTelemetry(link: NetworkLink): TelemetryPoint[] {
  const points = telemetryByLink[link.id];
  if (!points) throw new Error(`No generated telemetry for link "${link.id}" — run \`python -m netsense build-data\` in engine/.`);
  return points;
}

export interface LinkVitals {
  link: NetworkLink;
  now: TelemetryPoint;
  healthScore: number;
  anomalyScore: number;
  status: "healthy" | "attention";
  latencyDeltaMs: number;
  latencyDeltaPct: number;
  jitterDeltaMs: number;
}

function clamp(n: number, lo: number, hi: number) {
  return Math.min(hi, Math.max(lo, n));
}

/** Anomaly-score threshold above which a corridor is flagged for attention —
 *  shared by the link status calculation and every "Threshold: X (Exceeded)"
 *  readout so the page never shows a contradictory verdict. */
export const ANOMALY_ATTENTION_THRESHOLD = 0.22;

/** The rule-based scorer for one telemetry snapshot against a link baseline.
 *  Pure, so it can be checked against the Python engine on arbitrary inputs
 *  (engine/tests/test_parity_ts.py). Not a trained model. */
export function scoreSnapshot(now: TelemetryPoint, baseline: NetworkLink["baseline"]): Omit<LinkVitals, "link" | "now"> {
  const { latencyMs: bl, lossPct: blLoss, jitterMs: blJitter } = baseline;

  const latencyDeltaPct = (now.latencyMs - bl) / bl;
  const jitterDeltaMs = now.jitterMs - blJitter;
  const lossDeltaPct = now.lossPct - blLoss;

  // Each term is normalised to its own "notable excursion" scale and capped
  // at 1 before weighting, so the composite score stays a readable 0..1
  // regardless of how close to zero a metric's baseline happens to sit
  // (packet loss baselines are ~0.02%, so raw ratios would blow up).
  const latencyTerm = clamp(Math.max(0, latencyDeltaPct) / 0.5, 0, 1);
  const lossTerm = clamp(Math.max(0, lossDeltaPct) / 0.5, 0, 1);
  const jitterTerm = clamp(Math.max(0, jitterDeltaMs) / 2, 0, 1);
  const bandwidthTerm = clamp((now.bandwidthPct - 75) / 25, 0, 1);

  const anomalyScore = clamp(0.4 * latencyTerm + 0.3 * lossTerm + 0.15 * jitterTerm + 0.15 * bandwidthTerm, 0, 1);

  const healthScore = clamp(100 - anomalyScore * 38, 55, 100);
  const status: "healthy" | "attention" = anomalyScore >= ANOMALY_ATTENTION_THRESHOLD ? "attention" : "healthy";

  return {
    healthScore: Math.round(healthScore * 10) / 10,
    anomalyScore: Math.round(anomalyScore * 100) / 100,
    status,
    latencyDeltaMs: Math.round((now.latencyMs - bl) * 10) / 10,
    latencyDeltaPct: Math.round(latencyDeltaPct * 1000) / 10,
    jitterDeltaMs: Math.round(jitterDeltaMs * 10) / 10,
  };
}

export function computeVitals(link: NetworkLink): LinkVitals {
  const points = getTelemetry(link);
  const now = currentSnapshot(points);
  return { link, now, ...scoreSnapshot(now, link.baseline) };
}

export function allVitals(): LinkVitals[] {
  return LINKS.map(computeVitals);
}

export function networkBaselinePct(): number {
  const vitals = allVitals();
  const avg = vitals.reduce((s, v) => s + v.healthScore, 0) / vitals.length;
  return Math.round(avg * 10) / 10;
}

export function corridorsNeedingReview(): { total: number; flagged: number; vitals: LinkVitals[] } {
  const vitals = allVitals();
  return { total: vitals.length, flagged: vitals.filter((v) => v.status === "attention").length, vitals };
}
