import type { TelemetryPoint } from "./types";

// Telemetry is generated by the Python engine (engine/netsense/telemetry.py) and
// committed as app/src/data/generated/telemetry.json. This module holds only the
// profile names and the small helpers the screens use to slice a series.
//
// Sampling: every 30 minutes from t = -48h to t = +12h (121 samples). The t > 0
// samples are a synthetic continuation of the same profile, not a forecast model.

/** How a corridor's telemetry departs from baseline over the 48h trailing
 *  window and the +12h projection. Each link carries exactly one (see derive.ts). */
export type DriftProfile = "bifurcation" | "loss-degradation" | "saturation" | "oscillation" | "stable" | "recovering";

export function currentSnapshot(points: TelemetryPoint[]): TelemetryPoint {
  // "now" is t === 0
  return points.find((p) => p.t === 0) ?? points[points.length - 1];
}

export function historyOnly(points: TelemetryPoint[]): TelemetryPoint[] {
  return points.filter((p) => p.t <= 0);
}

export function projectionOnly(points: TelemetryPoint[]): TelemetryPoint[] {
  return points.filter((p) => p.t >= 0);
}
